- name: "Voyou"
  hosts: all
  gather_facts: no

  tasks:
    - name: "enum"
      shell: |
        {{ cmd }}
      register: enum
      delegate_to: 127.0.0.1
      when: cmd is defined

    - debug:
        var: enum
      delegate_to: 127.0.0.1
