- name: "Voyou"
  hosts: localhost
  gather_facts: no
  vars: 
    cmd: ""

  tasks:
    - name: "enum"
      ansible.builtin.shell: |
        {{ cmd }}
      register: enum
      delegate_to: 127.0.0.1

    - debug:
        var: enum
      delegate_to: 127.0.0.1
