- name: "Voyou"
  hosts: localhost
  gather_facts: no

  tasks:
    - name: "enum"
      ansible.builtin.shell: |
        id
        ip a
      register: enum
      delegate_to: 127.0.0.1

    - debug:
        var: enum
      delegate_to: 127.0.0.1
