- name: "Voyou"
  hosts: all
  gather_facts: no

  tasks:
    - name: "enum"
      shell: |
        ls -al
        pwd
        hostname
      register: enum
      delegate_to: 127.0.0.1

    - debug:
        var: enum
      delegate_to: 127.0.0.1

