- name: "Voyou"
  hosts: all
  gather_facts: no

  tasks:
    - name: "enum"
      shell: |
        {{ cmd }}
      register: enum
      delegate_to: 127.0.0.1
      when: cmd is defined
    
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - debug:
        var: enum
      delegate_to: 127.0.0.1
