- name: "Voyou"
  hosts: all
  gather_facts: no

  tasks:
    - name: "python"
      command: /usr/bin/python3
      args:
        stdin: |
          {{ code | b64decode }}
      register: pyout
      when: code is defined
      delegate_to: 127.0.0.1

    - debug:
        var: pyout
      delegate_to: 127.0.0.1

